name: Download Repo on Runner Machine
on: [push]

jobs:
  download_repo_actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files before
        run: ls -a
      - uses: actions/checkout@v3
      - name: List Files After
        run: ls -a

  download_repo:
    runs-on: ubuntu-latest
    steps:
      - name: List files before
        run: ls -a
      - name: Download Repo
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout master
      - name: List files after
        run: ls -a