name: Event Activity Types
on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    types: [opened, reopened, synchronize, assigned]
  issues:
    types: [opened]

jobs:
  display_github_details:
    runs-on: ubuntu-latest
    steps:
      - name: Github Details Display
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v3