name: Stale Issues and PR
on:
  schedule:
    - cron: '0 14 * * *'
    - cron: '0/5 * * * *'

jobs:
  stale-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
            stale-issue-message: 'This PR is stale'
            days-before-stale: 1
            days-before-close: 5
