name: "Workflow Commands"
on: [push]

jobs:
  wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: "Display Error Message"
        run: echo "::error::Missing Semicolon"
      - name: "Display Error Message with parameters"
        run: echo "::error title=Error Title,file=app.js,line=2,endline=3,col=5,endCol=7::Missing Semicolon"
      - name: "Display Debug Messages"
        run: echo "::debug title=Debug Title,file=app.js,line=2,endline=3,col=5, endCol=7::Missing Semicolon"
      - name: "Display Warning Messages"
        run: echo "::warning title=Warning Title,file=app.js,line=2,endline=3,col=5,endCol=7::Missing Semicolon"
      - name: "Display Notice Messages"
        run: echo "::notice title=Notice Title,file=app.js,line=2,endline=3,col=5,endCol=7::Missing Semicolon"
