name: Workflow Dispatch Event
on:
  workflow_dispatch:
    inputs:
      string:
        description: String Value
        required: true
        type: string
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  manual_workflow_dispatch:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_REF